### ISSUE TITLE
Does plas.io support LAS1.4?

### ISSUE THREAD

**Issue by brianbancroft** [verma/plasio#49]
Hi there, 

I've been playing with this from time to time, and I really enjoy it. 

I was wondering if at the current time, if plas.io supports las1.4? 

Thanks. Feel free to close this once you give the Y/N.

**Comment by mjernil** [comment]
is LAS 1.4 still not supported in plasio viewer?

**Comment by hobu** [comment]
plasio still does not support LAS 1.4, but it would now be possible to do so if someone updated the code to use the latest laz-perf library, which now includes javascript LAZ 1.4.
