### ISSUE TITLE
Dataset is displayed as a long stacked line of points

### ISSUE THREAD

**Issue by pierotofy** [verma/plasio#58]
Hello,

I was wondering if somebody could help me understand why some data is not displaying properly on plas.io, I'm thinking it's probably something funky with the dataset, but I just can't figure out what, or how to fix it.

I downloaded some datasets from coast.noaa.gov: https://coast.noaa.gov/htdata/lidar1_z/geoid12a/data/2507/

Taking as an example the first two files from the list of Point Cloud Data Files:
 - https://coast.noaa.gov/htdata/lidar1_z/geoid12a/data/2507/20090825_pt000542.laz
 - https://coast.noaa.gov/htdata/lidar1_z/geoid12a/data/2507/20090825_pt000541.laz

When I load them to plas.io I get a long line of points:

![image](https://cloud.githubusercontent.com/assets/1951843/23365304/92215564-fcd0-11e6-9e9f-90e1659930ec.png)

Other things I noticed:
 - If I perform a `pdal translate 20090825_pt000542.laz uncompressed.las` and load `uncompressed.las` into http://lidarview.com I get the same long line.
 - If I perform a `laszip -i 20090825_pt000542.laz -o uncompressed2.las` using LASTools and load `uncompressed2.las` into http://lidarview.com I get:

![image](https://cloud.githubusercontent.com/assets/1951843/23365130/d2bd69a6-fccf-11e6-8154-d074ad1dffb9.png)

PDAL returns the following with the info summary command:

```bash
root@7bca0abdf4b6:/lidar# pdal info --summary 20090825_pt000541.laz 
{
  "filename": "20090825_pt000541.laz",
  "pdal_version": "1.4.0 (git-version: c7cef9)",
  "summary":
  {
    "bounds":
    {
      "X":
      {
        "max": -90.96873434,
        "min": -90.97300214
      },
      "Y":
      {
        "max": 46.6097259,
        "min": 46.6022752
      },
      "Z":
      {
        "max": 244.868,
        "min": 195.739
      }
    },
    "dimensions": "X, Y, Z, Intensity, ReturnNumber, NumberOfReturns, ScanDirectionFlag, EdgeOfFlightLine, Classification, ScanAngleRank, UserData, PointSourceId, GpsTime",
    "num_points": 123644,
    "srs":
    {
      "compoundwkt": "COMPD_CS[\"unknown\",GEOGCS[\"NAD83\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS 1980\",6378137,298.2572221010002,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"6269\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433],AUTHORITY[\"EPSG\",\"4269\"]],VERT_CS[\"NAVD88 height\",VERT_DATUM[\"North American Vertical Datum 1988\",2005,AUTHORITY[\"EPSG\",\"5103\"],EXTENSION[\"PROJ4_GRIDS\",\"g2012a_conus.gtx,g2012a_alaska.gtx,g2012a_guam.gtx,g2012a_hawaii.gtx,g2012a_puertorico.gtx,g2012a_samoa.gtx\"]],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Up\",UP],AUTHORITY[\"EPSG\",\"5703\"]]]",
      "horizontal": "GEOGCS[\"NAD83\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS 1980\",6378137,298.2572221010002,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"6269\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433],AUTHORITY[\"EPSG\",\"4269\"]]",
      "isgeocentric": false,
      "isgeographic": true,
      "prettycompoundwkt": "COMPD_CS[\"unknown\",    GEOGCS[\"NAD83\",        DATUM[\"North_American_Datum_1983\",            SPHEROID[\"GRS 1980\",6378137,298.2572221010002,                AUTHORITY[\"EPSG\",\"7019\"]],            AUTHORITY[\"EPSG\",\"6269\"]],        PRIMEM[\"Greenwich\",0],        UNIT[\"degree\",0.0174532925199433],        AUTHORITY[\"EPSG\",\"4269\"]],    VERT_CS[\"NAVD88 height\",        VERT_DATUM[\"North American Vertical Datum 1988\",2005,            AUTHORITY[\"EPSG\",\"5103\"],            EXTENSION[\"PROJ4_GRIDS\",\"g2012a_conus.gtx,g2012a_alaska.gtx,g2012a_guam.gtx,g2012a_hawaii.gtx,g2012a_puertorico.gtx,g2012a_samoa.gtx\"]],        UNIT[\"metre\",1,            AUTHORITY[\"EPSG\",\"9001\"]],        AXIS[\"Up\",UP],        AUTHORITY[\"EPSG\",\"5703\"]]]",
      "prettywkt": "GEOGCS[\"NAD83\",    DATUM[\"North_American_Datum_1983\",        SPHEROID[\"GRS 1980\",6378137,298.2572221010002,            AUTHORITY[\"EPSG\",\"7019\"]],        AUTHORITY[\"EPSG\",\"6269\"]],    PRIMEM[\"Greenwich\",0],    UNIT[\"degree\",0.0174532925199433],    AUTHORITY[\"EPSG\",\"4269\"]]",
      "proj4": "+proj=longlat +datum=NAD83 +geoidgrids=g2012a_conus.gtx,g2012a_alaska.gtx,g2012a_guam.gtx,g2012a_hawaii.gtx,g2012a_puertorico.gtx,g2012a_samoa.gtx +vunits=m +no_defs",
      "units":
      {
        "horizontal": "metre",
        "vertical": "metre"
      },
      "vertical": "VERT_CS[\"NAVD88 height\",VERT_DATUM[\"North American Vertical Datum 1988\",2005,AUTHORITY[\"EPSG\",\"5103\"],EXTENSION[\"PROJ4_GRIDS\",\"g2012a_conus.gtx,g2012a_alaska.gtx,g2012a_guam.gtx,g2012a_hawaii.gtx,g2012a_puertorico.gtx,g2012a_samoa.gtx\"]],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Up\",UP],AUTHORITY[\"EPSG\",\"5703\"]]",
      "wkt": "GEOGCS[\"NAD83\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS 1980\",6378137,298.2572221010002,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"6269\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433],AUTHORITY[\"EPSG\",\"4269\"]]"
    }
  }
}
```

If this is not the right place to ask this question, please let me know. Thank you!

**Comment by m-schuetz** [comment]
> "max": -90.96873434,
> "min": -90.97300214

The extremely small range of your x and y coordinates compared to the range of your z coordinates indicates that x and y are likely in lat/long/angles and only the z coordinate is in meters. I don't know how exactly but if you can transform the data set so that all your coordinates are in meters, you'll get the expected result.

**Comment by lidar532** [comment]
Transform it to UTM, then try.  Ive seen the same thing from "Cloud Compare"


W Wright


“In theory, theory and practice are the same. In practice, they are not.”
-Albert Einstein

Cell: 443-783-3319
Fax: 603-994-8796

**Comment by pierotofy** [comment]
Thank you both! Once converted to UTM the data displayed properly (which makes sense, since UTM usually uses meters for its planar coordinates).

Cheers!

![image](https://cloud.githubusercontent.com/assets/1951843/23407621/d446acba-fd92-11e6-8419-bae2df64cabd.png)
