### ISSUE TITLE
Error while onstalling on Mac OS x

### ISSUE THREAD

**Issue by jmprovencher** [verma/plasio#59]
While installing on Mac, when typing sudo npm install in the directory, I get this error:
<img width="608" alt="capture d ecran 2017-08-24 a 11 12 41" src="https://user-images.githubusercontent.com/12234108/29673478-4cc6f536-88bd-11e7-90e4-a81a13a6cd9d.png">

**Comment by jcvtieck** [comment]
same here!

**Comment by verma** [comment]
Could be some issue with outdated dependencies.  I will take a look and push a fix.

Thanks for reporting.

**Comment by verma** [comment]
I have updated the dependencies to latest versions, along with whatever changes were necessary for things to compile and work again.

Please give it a shot.  I am not 100% sure if things are stilling working as expected.  If you do find something broken, please open a new issue.
